package ph.bxtdev.Zevix;

import android.app.Activity;
import android.content.Context;
import com.google.appinventor.components.annotations.*;
import com.google.appinventor.components.common.ComponentCategory;
import com.google.appinventor.components.runtime.*;
import com.google.appinventor.components.runtime.util.MediaUtil;
import android.graphics.drawable.Drawable;

@DesignerComponent(
        version = 1,
        description = "Extension made by Bxtdev, Made using the powerful Warlock!",
        category = ComponentCategory.EXTENSION,
        nonVisible = true,
        iconName = "")

@SimpleObject(external = true)
//Libraries
@UsesLibraries(libraries = "")
//Permissions
@UsesPermissions(permissionNames = "")

public class Zevix extends AndroidNonvisibleComponent {

    //Activity and Context
    private Context context;
    private Activity activity;

    public Zevix(ComponentContainer container){
        super(container.$form());
        this.activity = container.$context();
        this.context = container.$context();
    }

    @SimpleFunction(description = "Sample Function Generated by Niotron")
    public void SetImage(AndroidViewComponent imageComponent, String image){
        Drawable drawable = MediaUtil.getBitmapDrawable(container.$form(), image);
        if(imageComponent instanceof ImageView){
            ImageView i = (ImageView) imageComponent;
            i.setImageBitmap(drawable);
        }
    }
}
